name: Build & Deploy Sphinx (HTML + PDF)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          pip install -U pip
          pip install sphinx myst-parser pydata-sphinx-theme sphinx-copybutton

      - name: Install TeX + tools + fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            latexmk texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-xetex inkscape \
            fonts-dejavu fonts-freefont-ttf texlive-lang-european

      - name: Build HTML
        run: sphinx-build -b html docs site_html

      - name: Build LaTeX sources
        run: sphinx-build -b latex docs _build/latex

      - name: Build PDF with XeLaTeX
        run: |
          cd _build/latex
          TEXFILE="$(ls -1 *.tex | head -n1)"
          echo "Compilant $TEXFILE ..."
          latexmk -pdf -xelatex -interaction=nonstopmode -halt-on-error "$TEXFILE"
          cd -
          mkdir -p site_html/pdf
          cp _build/latex/*.pdf site_html/pdf/plantilla-sphinx.pdf

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site_html
          keep_files: true
